title: REDMAGIC Docs
description: Unofficial guides for REDMAGIC OS based Devices.
theme: just-the-docs
color_scheme: dark

url: https://therealcrazyfuy.github.io/RedmagicOSTricks

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: GitHub
    url: https://github.com/TheRealCrazyfuy/RedmagicOSTricks

aux_links:
  "Give us a ⭐":
    - "https://github.com/TheRealCrazyfuy/RedmagicOSTricks"

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/TheRealCrazyfuy/RedmagicOSTricks" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from

