title: REDMAGIC Guides
description: Unofficial guides for REDMAGIC OS based Devices.
theme: just-the-docs
color_scheme: dark

url: https://therealcrazyfuy.github.io/RedmagicOSTricks

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

nav_external_links:
  - title: Contribute
    url: https://github.com/TheRealCrazyfuy/RedmagicOSTricks

aux_links:
  "Give us a ⭐":
    - "https://github.com/TheRealCrazyfuy/RedmagicOSTricks"
