title: REDMAGIC Tricks
description: A website I made to share my knowledge about REDMAGIC devices.
theme: just-the-docs
color_scheme: dark

url: https://just-the-docs.github.io

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red